apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: ingest-hl7
  namespace: dev
spec:
  podSelector:
    matchLabels:
      app: ingest-hl7
  listeners:
    - portMapping:
        port: 5000
        protocol: http
  backends:
    - virtualService:
        virtualServiceRef:
          name: store
  serviceDiscovery:
    awsCloudMap:
      namespaceName: dev.svc.cluster.local
      serviceName: ingest-hl7