apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualRouter
metadata:
  namespace: dev
  name: store
spec:
  listeners:
    - portMapping:
        port: 5000
        protocol: http
  routes:
    - name: store-hl7-route
      http2Route:
        match:
          prefix: /
        action:
          weightedTargets:
            - virtualNodeRef:
                name: store-hl7
              weight: 1
