apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: store-hl7
  namespace: dev
spec:
  podSelector:
    matchLabels:
      app: store-hl7
  listeners:
    - portMapping:
        port: 5000
        protocol: http
  serviceDiscovery:
    awsCloudMap:
      namespaceName: dev.svc.cluster.local
      serviceName: store-hl7