apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: store-hl7
  namespace: dev
spec:
  podSelector:
    matchLabels:
      app: store-hl7
  listeners:
    - portMapping:
        port: 80
        protocol: http
  serviceDiscovery:
    dns:
      hostname: store-hl7.dev.svc.cluster.local