apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: ingest-hl7
  namespace: hl7
spec:
  podSelector:
    matchLabels:
      app: ingest-hl7
  listeners:
    - portMapping:
        port: 5000
        protocol: http  
  serviceDiscovery:
    dns:
      hostname: ingest-hl7.hl7-mesh.svc.cluster.local