apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev
  name: store-hl7
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store-hl7
  template:
    metadata:
      labels:
        app: store-hl7
    spec:
      serviceAccountName: hl7storeirsa
      containers:
        - name: store-hl7
          image: 279855623390.dkr.ecr.us-east-2.amazonaws.com/hl7_store:latest
          ports:
            - containerPort: 5000