apiVersion: v1
kind: Service
metadata:
  namespace: dev
  name: store-hl7
  labels:
    app: store-hl7
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 5000
  selector:
    app: store-hl7
