apiVersion: v1
kind: Service
metadata:
  namespace: hl7
  name: ingest-hl7
  labels:
    app: ingest-hl7
    tier: frontend
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 5000
  selector:
    app: ingest-hl7
    tier: frontend